//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Employes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dim_Employes()
        {
            this.TF_Absenteisme = new HashSet<TF_Absenteisme>();
        }
    
        public int Cle_CoreDataSet { get; set; }
        public Nullable<long> Employee_Number { get; set; }
        public string State { get; set; }
        public Nullable<long> Zip { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string MaritalDesc { get; set; }
        public string CitizenDesc { get; set; }
        public string Hispanic_Latino { get; set; }
        public Nullable<int> Ancienneté { get; set; }
        public string RaceDesc { get; set; }
        public string Reason_For_Term { get; set; }
        public string Employment_Status { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public Nullable<decimal> Pay_Rate { get; set; }
        public string Manager_Name { get; set; }
        public string Employee_Source { get; set; }
        public string Performance_Score { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> CP_DOB { get; set; }
        public Nullable<System.DateTime> CP_Date_of_Hire { get; set; }
        public Nullable<System.DateTime> CP_Date_of_Termination { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TF_Absenteisme> TF_Absenteisme { get; set; }
    }
}
