//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charts.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RHEntities : DbContext
    {
        public RHEntities()
            : base("name=RHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dim_Absences> Dim_Absences { get; set; }
        public virtual DbSet<Dim_DepEmp> Dim_DepEmp { get; set; }
        public virtual DbSet<Dim_Employes> Dim_Employes { get; set; }
        public virtual DbSet<Dim_Manager> Dim_Manager { get; set; }
        public virtual DbSet<Dim_Sex> Dim_Sex { get; set; }
        public virtual DbSet<Dim_Status> Dim_Status { get; set; }
        public virtual DbSet<Dim_StatusMarital> Dim_StatusMarital { get; set; }
        public virtual DbSet<TF_Absenteisme> TF_Absenteisme { get; set; }
    }
}
