//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TF_Absenteisme
    {
        public int Id { get; set; }
        public Nullable<int> Cle_CoreDataSet { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Copie_de_jrs_absence { get; set; }
        public Nullable<decimal> Taux { get; set; }
        public Nullable<decimal> Taux_Assiduite { get; set; }
        public Nullable<int> Id_Perf_Score { get; set; }
        public Nullable<int> id_manager { get; set; }
        public Nullable<int> id_statut { get; set; }
        public Nullable<int> id_sex { get; set; }
        public Nullable<int> id_marital { get; set; }
        public Nullable<int> id_absence { get; set; }
        public Nullable<int> id_dept { get; set; }
    
        public virtual Dim_Absences Dim_Absences { get; set; }
        public virtual Dim_DepEmp Dim_DepEmp { get; set; }
        public virtual Dim_Employes Dim_Employes { get; set; }
        public virtual Dim_Manager Dim_Manager { get; set; }
        public virtual Dim_Sex Dim_Sex { get; set; }
        public virtual Dim_Status Dim_Status { get; set; }
        public virtual Dim_StatusMarital Dim_StatusMarital { get; set; }
    }
}
